### ISSUE TITLE
sidebar fix?

### ISSUE THREAD

**Issue by deviashin** [iamshipon1988/bootadmin#1]
Hello!
Please tell me how to make sure that the state of the side menu (which is compressed when you click on the button next to the logo) retains its state when the page is reloaded? The option with localStorage would completely suit me, but I do not understand javascript at all.
I ask for a working code on how to do this. Editing someone else’s code is very difficult, but I’m not yet able to write my own :)
Most likely, if you help me, the second problem associated with this menu will also be solved. In the mobile version, when you reload the page, it always opens, which is terribly angry :)

**Comment by iamshipon1988** [comment]
Sorry for the late reply. The world is not as it was. If you are referring to having your sidebar closed by default (i.e. Icon View), the you just need to change the `sidebar-open` class on the `<body>` tag to `sidebar-closed`.

**Comment by deviashin** [comment]
Hello, this approach is also useful, thanks for the tip.
But I talked about maintaining the state of the menu when the page was reloaded, for example, when the page was first loaded, the menu was opened, the user clicks the minimize button, reloads the page, and the menu should remain minimized. At the moment, after rebooting, the menu again becomes open, can you offer a simple option on how to save the value “open” or “closed” in the local storage of the browser?

**Comment by iamshipon1988** [comment]
@deviashin, apologies for misunderstanding. You need to use jsCookie library for that. And add a simple class for the state class. https://github.com/js-cookie/js-cookie

Sample code: 
```
$(document).ready(function() {
    var body_class = $.cookie("body_class");
    if(body_class) {
        $("body").attr("class", body_class);
    }
    $(".menu-toggle").click(function() {
        $("body").toggleClass("sidebar-open sidebar-closed");
        $.cookie("body_class", $("body").attr("class"));
    });
});
```

**Comment by deviashin** [comment]
Hi
Thank you very much for your help!
For three days, I still could not get it to work. 
Apparently, I should pull my knowledge into JS and return to this later.

Regards

**Comment by iamshipon1988** [comment]
Hi @deviashin,
I just pushed an update to add the cookie functionality. Should be available soon.
